
general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]


[env]
TERM = "xterm-256color"


[window]
padding.x = 2
padding.y = 2

decorations = "None"

opacity = 0.5
blur = true


[font]
size = 16
normal.family = "ShureTechMono Nerd Font"

# Use Cmd+Left/Right to move by word
[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bb"  # ESC + b → move backward by word

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bf"  # ESC + f → move forward by word

# Use Alt+Left/Right to move to the beginning/end of the line
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u0001"  # Ctrl+A → beginning of line

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u0005"  # Ctrl+E → end of line

# Use Cmd+Backspace to delete the word before the cursor
[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0017"  # Ctrl+W (backward-kill-word)

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

# Option+, and Option+. for tmux window navigation
[[keyboard.bindings]]
key = "Semicolon"
mods = "Alt"
chars = "\u001b;"

[[keyboard.bindings]]
key = "Period"
mods = "Alt"
chars = "\u001b."
