
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]


[env]
TERM = "xterm-256color"


[window]
padding.x = 2
padding.y = 2

decorations = "None"

opacity = 0.3
blur = true


[font]
size = 19
normal.family = "ShureTechMono Nerd Font"
